classification: True
segmentation: False

wandb: True

num_classes_classification: 2
num_classes_segmentation: 22

image_size: [460, 700]
patch_size: [32, 32]

pad_mode: constant
augmentation: True
train_split: 0.7

model_name: vit_base_patch16_224
pretrained: False

gpus: 1
seed: 42
amp: True

data_dir: ./data/breakhis
magnification: 40X

amp_backend: 'native' # Do not change
accumulate_grad_batches: 8
grad_clipping: False
grad_max_norm: 1.0

max_epochs: 15
batch_size: 8
drop_rate: 0.3

learning_rate: 1e-3
eps: !!float 1e-8
beta_1: 0.99
beta_2: 0.999
weight_decay: !!float 1e-4
warmup_proportion: 0.15
val_check_interval: 0.5
log_interval: 1
