gpus: 1
seed: 42

amp: True
amp_backend: native
workers: 4

wandb: True
log_interval: 1
val_check_interval: 0.5

num_classes: 2
train_split: 0.7

max_epochs: 75
batch_size: 16
drop_rate: 0.3

accumulate_grad_batches: 8
grad_clipping: False
grad_max_norm: 1.0

scheduler: False
learning_rate: !!float 3e-5
eps: !!float 1e-8
beta_1: 0.99
beta_2: 0.999
weight_decay: !!float 1e-4
warmup_proportion: 0.15

image_size: [460, 700]
patch_size: [32, 32]

data_dir: dataset/crowdsourcing

pad_mode: constant
resize: True
augmentation: True

model_name: vit_base_patch32_384
pretrained: True

head_type: transformer
hidden_dim: 512
num_layers: 6
num_heads: 8