data_dir: combined
magnification: '40X'
augmentation: False
train_split: 0.7

model_class: vit_base_patch16_224
pretrained: False
checkpoint:
num_classes: 8
seed: 42

amp: True
device: 

num_epochs: 25
batch_size: 32

lr: 3e-5
eps: !!float 1e-8
beta_1: 0.99
beta_2: 0.999
weight_decay: !!float 1e-5

grad_clipping: False
grad_max_norm: 1.0
grad_accumulation_steps: 1

scheduler:
num_warmup_steps:

log_interval: 1
save_model: False