data_dir: dataset/breakhis
magnification: '40X'
augmentation: True
train_split: 0.7

model_name: vit_base_patch16_224
pretrained: True
checkpoint:
num_classes: 2
seed: 42

amp: True
device: 

num_epochs: 25
batch_size: 32

lr: 3e-5
eps: !!float 1e-8
beta_1: 0.99
beta_2: 0.999
weight_decay: !!float 1e-5

drop_rate: 0.0
attention_drop_rate: 0.0

image_size: [224, 224]

grad_clipping: False
grad_max_norm: 1.0
grad_accumulation_steps: 1

scheduler:
num_warmup_steps:

log_interval: 1
save_model: False 