data_dir: combined
magnification: '40X'
image_size: [460, 700]
patch_size: [32, 32]
pad_mode: constant
augmentation: True
train_split: 0.7

model_class: vit_base_patch32_224
pretrained: False
checkpoint:
num_classes: 2
seed: 42

amp: True
device: 'cuda'

num_epochs: 50
batch_size: 32

attn_drop_rate: 0.1
drop_rate: 0.4

learning_rate: 1e-3
eps: !!float 1e-8
beta_1: 0.99
beta_2: 0.999
weight_decay: !!float 1e-4

gradient_clipping: False
gradient_max_norm: 1.0
gradient_accumulation_steps: 8

scheduler: linear
num_warmup_steps: 5000

log_interval: 1
save_model: False
save_only_best: True